### ISSUE TITLE
Handle residue renaming by PTMs in the data inputs

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#128]
The code can rename a residue based on the PTMs detected on it. It then uses the `ForceField.renamed_residue` attribute that is a dict with `(resname, [modification_name, ...])` as key and the new resname as value. It is not possible to fill the attribute from the file format, yet.

One possible syntax would be to add a `rename` section in the definition of the modifications. Renaming "HIS" to "HSD" could then look like:

```
[ modification ]
HSD
[ atoms ]
ND1 {"resname": "HIS", "element": "N"} 
HD1 {"resname": "HIS", "element": "H", "PTM_atom": true}
[ edges ]
ND1 HD1
[ rename ]
HIS HSD ; first name is the residue name before, second is resname after
```

This would add `{('HIS', ['HSD']): 'HSD'}` to `ForceField.renamed_residue`.

Though, this solution would fail when more than 1 modification is detected on a residue. In the case of a HSD on the C-terminal, for instance, we would need to have `{('HIS', ['HSD', 'C-term']): 'HSD'}`. The syntax could then be:

```
[ rename ]
HIS HSD
HIS C-term HSD
HIS N-term HSD
```

Here, the first name is the name of the residue before renaming, the last name is the name after residue, and all names in between are names of other modifications to be present. Each line is a different possible scenario.

**Comment by pckroon** [comment]
Option b: separate the renaming from the PTM itself.

The PTM in your example is called HSD, so that's the tag that will be applied to the residue. Now there should be some sort of renaming section (somewhere), e.g. like this:

```
[ rename ]
HIS HSD: HSD
HIS HSD ACE: HDA
AA ACE: ACE
```

This would allow for macro expansion (AA) as well. And, in case multiple matches would be possible the last one is applied?

**Comment by jbarnoud** [comment]
@pckroon That is indeed a viable option. One thing I like about my proposal is that it keeps the modification somewhat self-contained. But it indeed can break. With yours, the 'rename' section can pretend it is part of the modification without really being. Works for me.
