### ISSUE TITLE
Links cannot remove nodes

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#136]
While it is possible to remove an atom using a modification (PTM) by having `{'replace': {'atomname': None}}` in the node attributes, the same trick does not work with links. It should. Doing the same thing with a link just sets the 'atomname' attribute to `None` which causes problem down the line.

**Comment by jbarnoud** [comment]
This requires #137 to be fixed.

**Comment by NanduTej** [comment]
I want to give this a try now.

**Comment by pckroon** [comment]
Go for it :)
It's somewhere around here: https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/processors/do_links.py#L284

**Comment by NanduTej** [comment]
Please you explain the problem a little bit more to me. I was not able to completely figure it out.

**Comment by pckroon** [comment]
Ok, let's see. Links are small graphs that are applied to a large graph (molecule), wherever they fit. We find where they fit using subgraph isomorphisms. All the places a link fits on molecule are stored in `matches` in the part of the code I linked. `matches` is a collection (probably a list) of dictionaries mapping  `{link_node: molecule_node}`. Link nodes describe changes (new properties) to molecule nodes in their `'replace'` attribute. One of the possible replacements is to remove the node from the molecule.
Such a link node (`node_attrs` in the code) could look like this: `{'replace': {'atomname': None}, 'atomname': 'HG', 'element': 'H', 'resname': 'CYS'}`. The properties besides `'replace'` determine where the link is applied on the molecule and you can ignore those. Whenever the `'atomname'` of a node is to be replaced with `None`, the node (`node_mol`) should be removed instead.

**Comment by pckroon** [comment]
Closed by #164.
