### ISSUE TITLE
`Molecule.remove_node` does not remove the interactions

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#137]
`Molecule.remove_node` and `Molecule._remove_nodes_from` remove the nodes and the edges. It does not touch the interactions, though; therefore leaving orphan interactions that cause issues latter on.

Removing a node should, at least by default, remove the corresponding interactions. We can think about having a switch to disable the behaviour if we want to keep the dangling interactions (relevant for #16 maybe?).

**Comment by NanduTej** [comment]
Hey @jbarnoud, I am a beginner and would like to contribute. If this issue is still up, please help me with how to get started.

**Comment by jbarnoud** [comment]
@NanduTej Thank you for your interest. We indeed interested in having this issue solved and you are welcome to give it a try.

The `Molecule` class in `vermouth/molecule.py` inherit from `networkx.Graph`. It gets the `remove_node` and `remode_nodes_from` method from that parent class. Though we do have additional logic in our class that `remove_node` does not take into account. What matters here, is that interactions in `Molecule.interactions` should be removed if they refer to nodes that are removed by `remove_node`.

**Comment by pckroon** [comment]
Note that you'll need to add both a `remove_node` *and* a `remove_nodes_from` method. The methods inherited from `Graph` don't use one another.

**Comment by NanduTej** [comment]
Okay, I did not completely get a hang of it. Can we connect somewhere? I would need some help as this is my first bug.

**Comment by pckroon** [comment]
Hey @NanduTej,

where's the difficulty? If there's unclarity regarding vermouth we're happy to help and give pointers. Unfortunately, due to time constraints, we can't really help you with general Python/OOP or git/GitHub questions.
In general, you'll need to add 2 methods to the `Molecule` class: `remove_node` and `remove_nodes_from`. Each of those should both call the parent method (`super().remove_node(...)` and `super().remove_nodes_from(...)`, as well as removing the required interactions from `Molecule.interactions`. 
`Molecule.interactions` is a dict of `{interaction_type: list of Interaction}`. `interaction_type` is a string (`'bonds'`, `'angles'`, ...), and `Interaction` is a `namedtuple` with attributes `atoms`, `parameters` and `meta` (https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/molecule.py#L28). You're only interested in the `atoms` attribute. If the node-to-be-removed is in `Interactions.atoms` the interaction should be removed from `Molecule.interactions` (you'll get bonus points if you manage to *remove* the interactions instead of making a new list).

Fortunately there's not really a time constraint on this issue, we don't need this functionality soon (hopefuly). We'll let you know (here) once that changes. Let us know if you want to give this a try, or if you rather give it back.

PS. we're fairly strict on code style/standards, so it could be that you produce a brilliant implementation, but still get a lot of comments on it. Don't despair :)

**Comment by jbarnoud** [comment]
@pckroon was faster that me at replying. I put my reply here anyway:

> Can we connect somewhere?

I am very sorry, I do not have the time at the moment. I can give you some more keys, though.

The `Molecule` class now gets its `remove_node` and `remove_nodes_from` methods from its class parent `networkx.Graph`. These inherited methods do not cover all our needs. Therefore, they need to be redefined in the `Molecule` class to do the following things:

* call the parent method using `super`;
* filter out the interactions that reference the nodes that get removed.

The interactions are stored in the `Molecule.interactions` attribute. It is a dictionary in which keys are interactions types as string (the name of a kind of interaction, it is usually "bonds", "angles", or any name; it does not really matter), and in which the values are lists of `Interaction` named tuples.

The `Interaction` named tuple defined a field "atoms" that refer to a list of node keys. (We call "node key" the name that networkx uses to access a given node in a graph.) The `remove_node` and `remove_nodes_from` methods must remove from `Molecule.interactions` all the instances of `Interaction` that refer to the nodes to remove in their "atoms" field.

**Comment by NanduTej** [comment]
Thanks for comments @jbarnoud and @pckroon. I think I have a better idea now. I will get back to you if I have more questions.

**Comment by NanduTej** [comment]
Hi, I wrote the code for this and want to test it. What would be the way to do that?

**Comment by pckroon** [comment]
Hey,

You can get some inspiration from the files in `vermouth/tests`. I'd like you to write tests as part of your PR anyway, so you might as well do it now. 
There's a few testcases I can think of right off the bat:

- Molecule with no nodes
- Molecule with nodes but no interactions
- Molecule with interactions that all need to be removed
- Molecule with interactions of which some need to be removed
- Molecule with interactions of which none need to be removed
- Molecule with interactions of different types (bonds and angles) of which all need to be removed
- Molecule with interactions of different types of which some need to be removed
- Molecule with interactions of different types of which none need to be removed

**Comment by NanduTej** [comment]
Okay, got it. Thanks!

**Comment by pckroon** [comment]
@NanduTej Any progress? Anything we can do to help?

**Comment by NanduTej** [comment]
Sorry for slacking off. I could not finish writing the test cases and run them properly. I think I had a problem in setting the dev environment properly. Can you please help me with how to do that?

**Comment by pckroon** [comment]
No worries, there's no rush from our end.

Here's what I think you need to do; you might have already done some steps though.
 - Clone/fork our repository on github
 - Make a local clone of your github repo
 - Make a virtual Python environment (see google, depends on your OS and setup)
 - Activate the virtual environment
 - `cd vermouth-martinize`
 - `pip install -e .`
 - `pip install -r requirements-tests.txt -r requirements-docs.txt`
 - Make your changes
 - `pytest vermouth/tests`
Once the tests pass:
 - Commit your changes
 - Push your changes to your github repo
 - Open a PR

**Comment by NanduTej** [comment]
Got it. Thanks for your guidance. I'll come back to you soon.

**Comment by pckroon** [comment]
I forgot a step (oops). I updated my comment above.

**Comment by NanduTej** [comment]
Hey. A test called test_dssp is failing even though I made no changes in relation to that. I will push the branch and can you check and tell me if there are issues and if the changes look good.

**Comment by NanduTej** [comment]
I am not able to push my branch. How should I upload the code for review?

**Comment by jbarnoud** [comment]
You cannot push to the main repository. Though, you can push to a fork. If you you did not fork the repository already, then you should click the fork button somewhere at the top of the github page. This will create a copy of the repository under your user. You should be able to push to that repository and create a pull request from there against the main repository. Le 7 nov. 2018 6:38 PM, Teja Nanduri <notifications@github.com> a écrit :I am not able to push my branch. How should I upload the code for review?

**Comment by NanduTej** [comment]
I am not able to add reviewers onto the list. So here is the url for my PR- https://github.com/marrink-lab/vermouth-martinize/pull/157.

**Comment by pckroon** [comment]
Fixed by #157
