### ISSUE TITLE
resids are not kept

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#154]
The resids are not kept from the input structures into the result file. This is a problem as resids are used by the users to relate their output structure with the input one, and with the literature.

One fix would be to add the resid in the `attribute_keep` argument of `do_mapping` and its corresponding processor. Though, it I recall correctly, we lost the resid because it could break mappings spanning across residues.

**Comment by NanduTej** [comment]
Hey, Can I pick this up?

**Comment by pckroon** [comment]
It may be better if @jbarnoud and me first have a short discussion on what we want this to do in the first place. His comment
> Though, it I recall correctly, we lost the resid because it could break mappings spanning across residues.

does indeed create issues here that require some thought. How good is your polymer chemistry/bioinformatics? ;)

**Comment by NanduTej** [comment]
> It may be better if @jbarnoud and me first have a short discussion on what we want this to do in the first place. His comment
> 
> > Though, it I recall correctly, we lost the resid because it could break mappings spanning across residues.
> 
> does indeed create issues here that require some thought. How good is your polymer chemistry/bioinformatics? ;)

Pretty bad actually. I haven't done any chemistry in 4/5 years. :sweat_smile:

**Comment by pckroon** [comment]
Hey,

after a discussion with @jbarnoud we decided that the mapping processor needs a rather sizable overhaul. It would be a waste of your time and effort if you fix this now since it's going to change anyway. I'll fix this while I deal with #165.

**Comment by pckroon** [comment]
Also, as a note to myself: there are three cases, to be picked by the user:
1) Renumber everything
2) Keep everything the same as much as possible. If we write a file format that does not support insertion codes, and we have ambiguous residues (same name and number) at the end, give a warning.
3) Renumber with an offset based on the first resid.
