### ISSUE TITLE
Links for protein termini not working as intended

### ISSUE THREAD

**Issue by pckroon** [marrink-lab/vermouth-martinize#160]
Links for protein termini are currently defined as follows:
```
[ link ]
[ molmeta ]
neutral_termini not(true)
[ features ]
neutral_termini
[ atoms ]
BB {"replace": {"atype": "Qd", "charge": 1}}
[ non-edges ]
BB -BB

[ link ]
[ molmeta ]
neutral_termini not(true)
[ features ]
neutral_termini
[ atoms ]
BB {"replace": {"atype": "Qa", "charge": -1}}
[ non-edges ]
BB +BB
```

This means that an amino acid will have it's charge changed even if it has a bond to something that happened to be called differently than a 'BB'. This become rather tedious if there's non-standard residues involved. This can be resolved by adding the following to both links:
```
[ pattern ]
BB {"resname": $protein_resnames}
```
A better solution still would be to the number of bonds somehow.

**Comment by pckroon** [comment]
An even better solution would be to look at the modifications found, and take it from there.

**Comment by jbarnoud** [comment]
I agree that `[ non-edge ]` is not ideal as it forces to make assumptions.

> A better solution still would be to the number of bonds somehow.

Rarely a good idea when you deal with coarse grained model. Assuming the number of bonds is at least as bad as assuming the name of the next bead.

We could count the edges on the residue graph. But it would be very *ad-hoc*.

> An even better solution would be to look at the modifications found, and take it from there.

It would work. Though, in the specific case of the termini, the treatment is likely to be user based and not in accordance to what is in the source structure.
