### ISSUE TITLE
Tests need to run martinize2

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#183]
#103 broke martinize2, this would not happen if martinize2 was executed during the tests.

**Comment by pckroon** [comment]
Was this fixed in #184, or do you want something more extensive?

**Comment by jbarnoud** [comment]
I'd like a couple of real calls, with a basic check that the right files are produced. I am hesitant about checking the content of the files.

**Comment by pckroon** [comment]
The file content should be covered by different tests anyway.
Although one full integrative test with a test_ff where the filecontents *are* validated is probably a good idea. It doesn't have to test all options exhaustively though.

**Comment by fgrunewald** [comment]
This would be the ideal place for Paulo's test set on Martini3 proteins. If we can do them we most likely can do atomistic as well.
