### ISSUE TITLE
MakeBonds needs more intelligence

### ISSUE THREAD

**Issue by pckroon** [marrink-lab/vermouth-martinize#202]
Currently MakeBonds makes bonds between all atoms within the vdw cutoff. This often makes too many edges, causing a lot of errors further down the line. In addition, it happily clobbers PDB TER records.
1) MakeBonds should run on Molecules, ~and the PDB reader should return separate molecules if they are separated by TER records~. This is fairly easy. EDIT: done by #211. MakeBonds *should* overrule TER records and merge separate molecules (but also see my next comment), but give a clear message when it merges two molecules because atoms X and Y are close together.
2) Making bonds should be guided by either:
    - atom names (undesirable because unreliable), or 
    - element and associated valence (really hard, and very specific to atomistic input). This sounds like a constrained integer programming problem (I'm not sure whether it's linear or quadratic): bonds are either 0, 1, 2 or 3, and all valences must be filled as much as possible. This gets muddled by charges which change the valence; and by secondary geometric criteria such as angles. To make it extra hard, I veto cvxopt and scipy as hard dependencies. On the other hand, maybe the greedy option (make bonds to the n closest atoms) already works well.
    - A geometric overlay/fit with reference conformations of residues. Opens a whole new can of worms regarding the conformational space a residue can sample, and what kind of data has to be provided by the user.

I don't see a way that is both independent from atom names, *and* works for coarse-grained input, because then it effectively becomes the same issue as identifying atoms to make the correct bonds --- which RepairGraph solves by using the bonds.

Maybe it should be more likelihood based (it's 85% likely that there is a bond between these two atoms), fueled by geometry (distance (and angles?)), atom names, valences, etc. Not sure what this would look like in the end though.

**Comment by pckroon** [comment]
In addition, it seems the current incarnation of MakeBonds is too eager to split disconnected components into separate molecules. 
For example, a protein of which one atom is far away from all other atoms (because rebuilding coordinates is hard for EM/modeler?). This will cause MakeBonds to (correctly) identify 2 separate connected components, one containing many atoms (let's call it A), and one containing 1 (or a few) atom (B). Then, RepairGraph will effectively start duplicating atoms. To A the atoms from B will be added; to B some atoms from A will be added (and afterwards, CanonicalizeModifications blows up with a KeyError traceback, but besides the point). 
If instead MakeBonds by magic identifies that A and B should remain 1 molecule, RepairGraph will flag it as a crazy modification, and CanonicalizeModification will give an interpretable error message.
However, and here's the crux, if you don't have a simple protein/polymer but a bunch of small molecules, you *want* them to be split according to connected components, and the information you get from the PDB file is probably not reliable enough to assume all molecules will be split by a TER, or similar. So the question is, given 2 (n?) disconnected fragments, are they part of the same molecule?

**Comment by Tsjerk** [comment]
This can only be solved by taking the residue identifier (residue name, chain, and number) into account, on a local basis: a block of one residue based on that identifier should not be split into fragments (or it should be recognized later that these are probably the same block, because they have the same identifier. This only gives the requirement that separate molecules must have separate identifiers, but so far the PDB (and the GRO file) should be reliable enough.
