### ISSUE TITLE
Backward errors

### ISSUE THREAD

**Issue by yongwangCPH** [marrink-lab/vermouth-martinize#212]
Is the backmapping function available? I tried to use backward5 and the mapping files of v. 3.0.4, but got the errors as follows:

Error reading charmm27 to martini mapping for PHE (file: backward-v5/Mapping/asn.charmm36.map).
Error reading charmm36 to martini mapping for PHE (file: backward-v5/Mapping/asn.charmm36.map).
Error reading charmm27 to martini mapping for ASN (file: backward-v5/Mapping/gln.charmm36.map).
Error reading charmm36 to martini mapping for ASN (file: backward-v5/Mapping/gln.charmm36.map).
Error reading charmm27 to martini mapping for GLN (file: backward-v5/Mapping/leu.charmm36.map).
Error reading charmm36 to martini mapping for GLN (file: backward-v5/Mapping/leu.charmm36.map).
Error reading charmm27 to martini mapping for LEU (file: backward-v5/Mapping/lys.charmm36.map).
Error reading charmm36 to martini mapping for LEU (file: backward-v5/Mapping/lys.charmm36.map).
Error reading charmm27 to martini mapping for LYS (file: backward-v5/Mapping/tyr.charmm36.map).
Error reading charmm36 to martini mapping for LYS (file: backward-v5/Mapping/tyr.charmm36.map).
Error reading charmm27 to martini mapping for TYR (file: backward-v5/Mapping/ala.charmm36.map).
Error reading charmm36 to martini mapping for TYR (file: backward-v5/Mapping/ala.charmm36.map).
Error reading charmm27 to martini mapping for ALA (file: backward-v5/Mapping/pro.charmm36.map).
Error reading charmm36 to martini mapping for ALA (file: backward-v5/Mapping/pro.charmm36.map).
Error reading charmm27 to martini mapping for PRO (file: backward-v5/Mapping/gly.charmm36.map).
Error reading charmm36 to martini mapping for PRO (file: backward-v5/Mapping/gly.charmm36.map).
Error reading charmm27 to martini mapping for GLY (file: backward-v5/Mapping/ile.charmm36.map).
Error reading charmm36 to martini mapping for GLY (file: backward-v5/Mapping/ile.charmm36.map).
Error reading charmm27 to martini mapping for ILE (file: backward-v5/Mapping/cys.charmm36.map).
Error reading charmm36 to martini mapping for ILE (file: backward-v5/Mapping/cys.charmm36.map).
Error reading charmm27 to martini mapping for CYS (file: backward-v5/Mapping/glu.charmm36.map).
Error reading charmm36 to martini mapping for CYS (file: backward-v5/Mapping/glu.charmm36.map).
Error reading charmm27 to martini mapping for GLU (file: backward-v5/Mapping/asp.charmm36.map).
Error reading charmm36 to martini mapping for GLU (file: backward-v5/Mapping/asp.charmm36.map).
Error reading charmm27 to martini mapping for ASP (file: backward-v5/Mapping/trp.charmm36.map).
Error reading charmm36 to martini mapping for ASP (file: backward-v5/Mapping/trp.charmm36.map).
Error reading charmm27 to martini mapping for TRP (file: backward-v5/Mapping/arg.charmm36.map).
Error reading charmm36 to martini mapping for TRP (file: backward-v5/Mapping/arg.charmm36.map).
Error reading charmm27 to martini mapping for ARG (file: backward-v5/Mapping/met.charmm36.map).
Error reading charmm36 to martini mapping for ARG (file: backward-v5/Mapping/met.charmm36.map).
Error reading charmm27 to martini mapping for MET (file: backward-v5/Mapping/thr.charmm36.map).
Error reading charmm36 to martini mapping for MET (file: backward-v5/Mapping/thr.charmm36.map).
Error reading charmm27 to martini mapping for THR (file: backward-v5/Mapping/val.charmm36.map).
Error reading charmm36 to martini mapping for THR (file: backward-v5/Mapping/val.charmm36.map).
Error reading charmm27 to martini mapping for VAL (file: backward-v5/Mapping/his.charmm36.map).
Error reading charmm36 to martini mapping for VAL (file: backward-v5/Mapping/his.charmm36.map).
Error reading charmm27 to martini mapping for HIS (file: backward-v5/Mapping/ser.charmm36.map).
Error reading charmm36 to martini mapping for HIS (file: backward-v5/Mapping/ser.charmm36.map).
Error reading charmm27 to martini mapping for SER (file: backward-v5/Mapping/ser.charmm36.map).
Error reading charmm36 to martini mapping for SER (file: backward-v5/Mapping/ser.charmm36.map).
Residues defined for transformation from martini to charmm27:
['CYS', 'HIS', 'SER', 'GLN', 'LYS', 'PRO', 'ARG', 'THR', 'PHE', 'ASN', 'GLY', 'ILE', 'LEU', 'TRP', 'ASP', 'ALA', 'VAL', 'GLU', 'TYR', 'MET']
Problem determining mapping coordinates for atom HA of residue ASP.
atomlist: ['N', 'CA', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'OD1', 'OD2', 'C', 'O']
want: HA ['!BB']
have: ['SC1', 'BB']
Bailing out...
['HA', 'CB', 'HB1', 'HB2', 'CG', 'OD1', 'OD2', 'C', 'O']

**Comment by Tsjerk** [comment]
Backward is not yet integrated in Vermouth/Martinize2. But it may be worth trying the Backward version on github: https://github.com/Tsjerk/Backward

I'll leave the issue standing as the integration is an objective.

**Comment by yongwangCPH** [comment]
Thanks for the quick response, Tsjerk. 
Struggled to remove the solvent and ions parts in the script, then it works!

**Comment by fgrunewald** [comment]
I assume this is closed?
