### ISSUE TITLE
SectionParser metaclass populates ALL subclasses with  ALL subclass methods

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#238]
Hi,

As already mentioned in PR #237 the metaclass SectionParser is broken or at least does not behave as one would expect. In PR #237 I described that the new ITP reader suddenly overwrites the arguments of the FF reader and vice versa. This appears to be a general issue with any random subclass that is part of the SectionLineParser. 

To make things even more obscure by loading  `vermouth.force-field` one also imports all different input parsers (at the moment .rtp and .ff). The loading of these input parsers triggers the setting of the `METH_DICT` through the meta-class. Thus by doing `import forcefield` one already implicitly sets the `METH_DICT` for any subclass defined  or imported at a later stage.  

I'll investigate further and feed this issue as I collect more information. 

Cheers,
Fabian

**Comment by fgrunewald** [comment]
So I figured out why this happens mostly by holistic debugging. I have no idea why or how that even happens. But it must have been intentionally. Anyways not overwriting the METH_DICT when a new class is created basically causes this cross exchange of methods. The culprit is the following line:
 https://github.com/marrink-lab/vermouth-martinize/blob/019fb3130e46523a695447573239f66c5e1d04fe/vermouth/parser_utils.py#L37 
Just removing the line and creating a dictionary every time anew works just fine. PR #237 get's rid of this issue.

**Comment by pckroon** [comment]
Although it's definitely an improvement over the status quo, I expect it's a partial fix. IIRC the `if` was there to make sure decorated methods are inherited.

**Comment by fgrunewald** [comment]
Doesn't break any of the tests though. Also why would you want to inherit all methods from all sub-classes of that given class? The methods are inherited by a given subclass from section line parser anyways.

**Comment by pckroon** [comment]
```python3
class A(metaclass=SectionLineParser):
    @SectionLineParser.section_parser('a')
    def method_a(self):
        ...

class B(A):
    @SectionLineParser.section_parser('b')
    def method_b(self):
        ...
```
Class B should also have methods registered for both sections a and b.

I'll try to analyse the behaviour a bit further, and if I find it make a test.

**Comment by fgrunewald** [comment]
@pckroon what is the verdict on this issue? I haven't encountered any problems with the fix we implemented this far. I think its fine. I also have subclassed other readers without problems.
