### ISSUE TITLE
ToMolecule drops meta data of interactions

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#244]
Hi, 

The following statement in ToMolecule causes meta data to be dropped when a block is converted to a Molecule. I'd say there is no reason for doing so or am I mistaken? It's kind of annoying, if you want to convert blocks with #ifdef statements for example. 

https://github.com/marrink-lab/vermouth-martinize/blob/019fb3130e46523a695447573239f66c5e1d04fe/vermouth/molecule.py#L1166-L1169

**Comment by pckroon** [comment]
I can't think of a valid reason. Looks like a valid bug.
