### ISSUE TITLE
DSSP error (duplicated nr. of residues)

### ISSUE THREAD

**Issue by gcourtade** [marrink-lab/vermouth-martinize#252]
I'm getting the following error. The protein has 156 residues. So it appears that at some step, they are being incorrectly duplciated.

```
Traceback (most recent call last):
  File "/lustre1/work/courtade/software/miniconda3/envs/py37/bin/martinize2", line 669, in <module>
    entry()
  File "/lustre1/work/courtade/software/miniconda3/envs/py37/bin/martinize2", line 545, in entry
    AnnotateDSSP(executable=args.dssp, savedir='.').run_system(system)
  File "/lustre1/work/courtade/software/miniconda3/envs/py37/lib/python3.7/site-packages/vermouth/processors/processor.py", line 38, in run_system
    mols.append(self.run_molecule(molecule))
  File "/lustre1/work/courtade/software/miniconda3/envs/py37/lib/python3.7/site-packages/vermouth/dssp/dssp.py", line 444, in run_molecule
    annotate_dssp(molecule, self.executable, self.savedir)
  File "/lustre1/work/courtade/software/miniconda3/envs/py37/lib/python3.7/site-packages/vermouth/dssp/dssp.py", line 277, in annotate_dssp
    annotate_residues_from_sequence(molecule, attribute, secstructs)
  File "/lustre1/work/courtade/software/miniconda3/envs/py37/lib/python3.7/site-packages/vermouth/dssp/dssp.py", line 390, in annotate_residues_from_sequence
    raise ValueError(msg.format(len(sequence), len(residues)))
ValueError: The sequence length does not match the number of residues. The sequence has 156 elements for 312 residues.
```
I tried with a different PDB file, it throws the same error.

Edit: The error was triggered by reading a PDB without hydrogens (incorrectly defined termini?). I managed to solve it by running pdb2gmx on the all-atom coordinates before martinizing

**Comment by fgrunewald** [comment]
Hi, 

Thanks for reporting this issue. Could you provide both the working and the not working pdb file?

Cheers,
Fabian

**Comment by gcourtade** [comment]
Hi Fabian,

Thanks, here are the files
[Martinize2-dssp.zip](https://github.com/marrink-lab/vermouth-martinize/files/4499710/Martinize2-dssp.zip)

Cheers,
Gaston

**Comment by pckroon** [comment]
Hi @gcourtade,

thanks indeed for the report. I'm happy you found a workaround in the meantime. Do you have for us:
1) The command line you used?
2) The full output of that (with debug output, so add `-v`)
3) The version of martinize2 (`martinize2 --version`)
4) The version of DSSP

Thanks in advance.

**Comment by gcourtade** [comment]
Hi @pckroon,

Thanks for the follow up.

1. The command line
```
martinize=$miniconda3/envs/py37/bin/martinize2 
dssp=$miniconda3/envs/py37/bin/mkdssp
FF=martini304

$martinize -f $pdb -o CG_topol.top -x CG.pdb -dssp $dssp -ff martini304 -ed -cys auto -elastic -scfix -ff-dir $ffdir/v.3.0.4.17/martini3-protein/force_fields/ -map-dir $ffdir/v.3.0.4.17/martini3-protein/mappings/ -v
```
2. The full output
[martinize-output.txt](https://github.com/marrink-lab/vermouth-martinize/files/4502140/martinize-output.txt)

3. martinize2 version 0.3.2.dev115

4. mkdssp version 3.0.0 installed from https://anaconda.org/salilab/dssp

**Comment by pckroon** [comment]
Thanks. Interesting, nothing really jumps out. This may take some time to track down. 
Thanks again for the report!

**Comment by pckroon** [comment]
Found it! The reconstructed hydrogens get sorted into their own residues, since repair_graph does not correctly set the `insertion_code`. For the reconstructed Hs it's None, for those from the PDB its `''`.
