### ISSUE TITLE
-cys auto is not working

### ISSUE THREAD

**Issue by paulocts** [marrink-lab/vermouth-martinize#263]
My current tests with vermouth 0.3.2.dev122 and martini22 models showed that -cys auto ist not working. The extra bond between the cysteine bridge was not added in the example a tested. In martinize1 works well.

**Comment by pckroon** [comment]
Follow up from email:
Between S-S we use 0.5*(1.8+1.8) = 1.8A as distance cutoff. Compared to e.g. VMD, that uses 0.6*(1.8+1.8) = 2.16A as cutoff. However, using the 20% fudge for all atoms will introduce other issues, the main of which is hydrogens making too many bonds. One way of fixing that would be to simply forbid H-H bonds.
