### ISSUE TITLE
Set neutral termini is only working for martini22

### ISSUE THREAD

**Issue by paulocts** [marrink-lab/vermouth-martinize#272]
Considering the default force-field options (elnedyn, martini22, etc), the only one that is properly working with the flag "-nt" is martini22. I guess the problem is the lack of modifications.ff and modifications.mapping files for other force-fields. I tried to adapt myself but did not work well.

Even if I try to use my version of martini 3 (providing additional repositories for mapping and force field files), -nt does not work.

**Comment by pckroon** [comment]
Should be fixed by now.
