### ISSUE TITLE
AnnoteMutMod fails with water present in pdb

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#275]
When water or any 1 residue molecule is present in the pdb file annotation of modifications and mutations fails, due to the fact that there are no neighbors in a residue graph with only one residue. Specifically the following line fails:

https://github.com/marrink-lab/vermouth-martinize/blob/67cfeb324a1b9c7c6d385f080766072a9802d7df/vermouth/processors/annotate_mut_mod.py#L111

**Comment by pckroon** [comment]
Fixed in #277
