### ISSUE TITLE
DeferredFileWriter complicates Vermouth as library

### ISSUE THREAD

**Issue by pckroon** [marrink-lab/vermouth-martinize#298]
The implementation of the DeferredFileWriter makes vermouth harder to use as a library, since e.g. write_gro doesn't write the file anymore until `DeferredFileWriter().write()` is called. The file writer should get an attribute, e.g. `immediate_write` which defaults to `True`. This attribute should cause files to get written immediately, but still making use of the backup mechanism. 
The easiest way is probably the creation of a `OpenFileWrapper` context manager which has the opened files as attribute, and an `__exit__` method that prompts writing. An mix-in class that gets added on the opened file object is an alternative, but probably overly complex.

**Comment by pckroon** [comment]
This is half-fixed in #394. The relevant writers have been given a keyword argument to toggle the use of the deferred writer. This loses the backup-file functionality, which is definitely on the list of nice-to-have things.
@Tsjerk Ideas? Long term I guess?

**Comment by fgrunewald** [comment]
This has been solved or not?
