### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by pckroon** [marrink-lab/vermouth-martinize#299]
There are currently no naming conventions in the library. The code is fine with this, but it complicates adoption. E.g. there are now modifications for ASP0 and GLU-H. We should pick a naming convention, and stick with it.

Note that there is no character limit of any kind for modification, since they're not written to PDB files anyway.

**Comment by fgrunewald** [comment]
we use charmm and amber default names. Users for now have to mutate the naming if they want to go from HIS to protonated HIS or something like that.
