### ISSUE TITLE
Fix python 2 compatibility

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#31]
It starts to be rather visible that we develop martinize2 using python 3; a few things are going to break python 2 users. At the very least I noted that we do not import `print_function` from `__future__`, and tend not to inherit from `object` when defining a class.

As we wanted version 1.0 to be compatible with python 2, we'll have to do some cleaning there.

**Comment by pckroon** [comment]
I think, but am not sure, that you don't need to inherit from `object` in 2.7, which will be the only py2 version we'll target. As for `ChainMap` and such, a lot of those got backported in pypi packages, so we can add those as py2 dependancies.

**Comment by jbarnoud** [comment]
Just tested what was supposed to be broken bu not inheriting from 
object. Surprisingly, it worked:

```python
class A:
     @property
     def plop(self):
         return 4

a = A()
a.plop
```

I actually wonder more and more if it only makes sense to be python2 
compatible. Python 3 is available by default in almost all distribution 
that will actually be used; it may be ubuntu's default by the time of 
release; and python 2 is very soon reaching the end of its life.

**Comment by pckroon** [comment]
As soon as we reach 1.0 we'll judge how much work it's going to be.

**Comment by jbarnoud** [comment]
Since you already tagged the issue as wontfix, I'll go one step further and close it.
