### ISSUE TITLE
Martinize2 cannot write the output files for debug

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#311]
If an error occurs that causes an exception, the deferred files are never written and there is no way to cause them to be from the command line. This makes debugging more difficult.

A solution would be to have a flag in the `DeferredFileWriter` singleton to cause the files to be written right away. That flag could be set with a `-debug` or `-no-defer` option in the command line.

**Comment by pckroon** [comment]
Related #298 
Yes, good argument. For now though, your files will survive in your temporary directory. 
It may also be a good idea to have the write-{canon,repair,graph} bypass the deferred writer. (Or better, have the writer write them immediately so the backup mechanism works).
