### ISSUE TITLE
CLI option to ignore alternate locations in PDB

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#313]
Currently, if there are alternate locations in a PDB input, then martinize issues a warning for each alternate location it encounters that is not `A` or empty. This means that if a PDB file uses alternate locations, then many warnings are issued, the number of which is only predictable by analysing the input file. These warnings are difficult to deal with in scripts because ignoring just these warnings means one needs to analyse the input files or run martinize twice to know how many warnings to ignore. This can easily lead to `-maxwarn 9999` being common in scripts.

A solution would be an option to choose the alternate, but this option is unlikely to be used. A simpler option is one that ignores alternates other than `A` or empty. This is the behaviour the most likely to be useful. I suggest `-ignore-alternate` with a default to `False`.

**Comment by pckroon** [comment]
Or: `-maxwarn inconsistent-data:9999` (`-maxwarn <type>[:amount]`).
The warning type for the alternates is not quite correct at the moment though

**Comment by jbarnoud** [comment]
Ignoring by type is indeed good. I would go as far as suggesting that amount can be `all` to avoid guessing a number.

**Comment by pckroon** [comment]
I'd say no number means all: `-maxwarn inconsistent-data`

**Comment by jbarnoud** [comment]
Question, though: if we have that, do we get rid of `-maxwarn N`?

**Comment by pckroon** [comment]
No, I'd say not. I think `-maxwarn N` should cover all warnings which are not covered by something more specific.
I.e. `-maxwarn inconsistent-data:10 2` should cover 10 inconsistent-data warnings, and 2 other warnings of any type.

**Comment by jbarnoud** [comment]
It is a tad confusing but OK.
