### ISSUE TITLE
PRO fail as N-Ter

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#315]
Martinize 2 cannot apply N-Ter modification to prollines. This hydrogen needs to become a PTM atom as well otherwise the modification is not recognized. This should probably be also changed for the NH2 modification. Example PDB is 4rma.

https://github.com/marrink-lab/vermouth-martinize/blob/c677535dca05bd848f59da292cd40affddecb49a/vermouth/data/force_fields/universal/modifications.ff#L32

**Comment by pckroon** [comment]
Closed as duplicate of #141
