### ISSUE TITLE
Display doi for citations

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#342]
When displaying the citation, displaying the doi when available would make citing easier.

**Comment by fgrunewald** [comment]
@jbarnoud we currently don't do that, because some dois (especially from Elsevier) are super long. This makes the screen-output unreadable and the itp header line very long. Perhaps we can come up with a better formatter

**Comment by fgrunewald** [comment]
they are now displayed.

**Comment by biomolsim** [comment]
@fgrunewald, would it be feasible to add the citation URLs to the main page also? It would make the citation easier, especially since my modelling output was produced before this update was implemented and since there are five papers mentioned in the list. Thank you very much.

**Comment by pckroon** [comment]
No, since the citations you get depends on your model and which forcefield elements (and possibly which processors) get used. You'll need to check the `citations.bib` files in the data folder.
