### ISSUE TITLE
Internal coordinates from molecule

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#357]
It should be possible to get internal coordinates from the definitions in the interactions of a molecule combined with it's graph representation. Having an attribute or function to extract those would be very cool and useful I believe. Manipulating coordinates are much easier in internal coordinates. However, I also realize that this is more like a long future goal, so I'll just leave this issue here so we remember. Potentially this is something for an upcoming hacktoberfest.

**Comment by pckroon** [comment]
I agree with this, mostly. The only issue I see is that it means we'll have to start interpreting (some of) the interaction parameters. Maybe this isn't too bad though, since we'd only need the equilibrium values, but even that may not be completely trivial for e.g. dihedrals with multiplicities.
