### ISSUE TITLE
CG DNA

### ISSUE THREAD

**Issue by philipford** [marrink-lab/vermouth-martinize#370]
Recently, I took Martini3 to run CG MD of protein with small molecules. The simulation works perfectly. Is it possible to generate CG DNA structures by using Martinize2 as well? Looks like there is only protein and lipid force field in the data folder. Where can we get the Martini3 force field and mapping files for DNA?

**Comment by pckroon** [comment]
Hello hello,

the code should have no problems with DNA, but AFAIK the models are still under development and not publicly available yet. Pinging @paulocts for confirmation.

**Comment by philipford** [comment]
Thanks, Peter. I will ask paulocts about the force field files.

**Comment by fgrunewald** [comment]
Dear all, 

Martini3 DNA parameters and mappings remain unpublished for the time being. Therefore we cannot distribute or provide mappings and/or parameters for DNA via martinize2. To get a preliminary model you can file a request with the corresponding author(s) of the Martini3 paper. We are aware that this is a less than ideal situation, however, as martinize2 developers our hands are tied in this regard.

Cheers,
Fabian
