### ISSUE TITLE
modifications (ASP0 and GLU0): not working

### ISSUE THREAD

**Issue by tozturkwashu** [marrink-lab/vermouth-martinize#376]
```WARNING - general - Can't find modification mappings for the modifications ['ASP0']. The following modification mappings are known: {('C-ter',): <vermouth.map_parser.Mapping object at 0x7f6f2b10cbe0>, ('N-ter',): <vermouth.map_parser.Mapping object at 0x7f6f2b1ff7f0>, ('COOH-ter',): <vermouth.map_parser.Mapping object at 0x7f6f2b10cda0>, ('NH2-ter',): <vermouth.map_parser.Mapping object at 0x7f6f2b10cf28>}```

It seems like ASP0 and GLU0 are listed as protein_resnames inside  ```aminoacids.ff``` file but modification mappings file doesn't contain information on them. How can we implement the protonated GLU and ASP models into ```martinize2```?

Thank you!

**Comment by pckroon** [comment]
The relevant mappings would have to be added to `vermouth/data/mappings/`. You can use e.g. `vermouth/data/mappings/modifications.mapping` as example. Unfortunately we don't have documentation for the file format(s) available at the moment.

**Comment by fgrunewald** [comment]
protonation states can be set by either naming the AAs correctly or by mutating the relevant residues to the protonated counterparts following amber or charmm naming convention.

**Comment by lorena-zuzic** [comment]
This seems to be an unsolved issue. In martini3001 ff, there are no parameters for either ASP0 and GLU0. They are listed as protein_resnames, but there are no [ moleculetype ] sections for either of the two. With a current installation of Martinize2 (from last week, using pip), I am getting the same error. 
 
Are the parameters for ASP0 (and GLU0) available somewhere? Currently, the only vermouth-implemented ff that has a defined ASP0 are elnedyn22, martini22, and martini22p, which is not helpful for Martini3.

**Comment by pckroon** [comment]
According to charmm naming convention these are called GLUP and ASPP, rather than GLU0 and ASP0.

**Comment by lorena-zuzic** [comment]
The issue remains: aminoacids.ff for Martini3 does not contain parameters for either of the two, so ASPP naming (tested below) does not work if the selected force field is martini3001. 

 WARNING - unmapped-atom - These atoms are not covered by a mapping. Either your mappings don't describe all atoms (bad idea), or, there's no mapping available for all residues. ['4417A-ASPP304:N', '4419A-ASPP304:CA', '4421A-ASPP304:CB', '4424A-ASPP304:CG', '4425A-ASPP304:OD1', '4426A-ASPP304:OD2', '4428A-ASPP304:C', '4429A-ASPP304:O']

**Comment by pckroon** [comment]
https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/data/force_fields/martini3001/aminoacids.ff#L230

What's the output of `martinize2 --version`?

**Comment by lorena-zuzic** [comment]
martinize with vermouth 0.7.3

**Comment by pckroon** [comment]
Ah right, those parameters have not been released to pypi yet, but it's fixed in master.
@fgrunewald I forgot if there was anything blocking a release, were we waiting for a PR/feature?

**Comment by pckroon** [comment]
Which modifications were that again? Is there already a PR or issue? I admit I lost track...

**Comment by lorena-zuzic** [comment]
Tried the dev version and works great - thanks a lot!
