### ISSUE TITLE
making cystein bridge with martinizie2

### ISSUE THREAD

**Issue by Byun-jinyoung** [marrink-lab/vermouth-martinize#386]
Hello martini users,
I have been trying to generate my protein system with cystein bridge.
But I encountered the error below:
```
Traceback (most recent call last):
  File "/home/byun/anaconda3/envs/MD_env/bin/martinize2", line 270, in _cys_argument
    result = float(value)
ValueError: could not convert string to float: 'A/22,A/92'
```

I used the command to generate martinized structure
`martinize2 -f ${i_crd}.pdb -ff martini3001 -scfix -p backbone -o ${i_crd}-cg.top -x ${i_crd}-cg.pdb -cys A/22,A/92`

How can I this problem???
I kindly request your suggestion :)

Thank you

**Comment by Tsjerk** [comment]
This issue has been solved. But I can't readily see when.

**Comment by biomolsim** [comment]
Hello Martinize developers,

Instead of adding a `CONECT` entry to the `.pdb` file, I would prefer to add a line for the desired cysteine-cysteine disulfide linkage to the `.itp` file. Any thoughts regarding this? Thanks.
