### ISSUE TITLE
Sequential distance between two residues for elastic network

### ISSUE THREAD

**Issue by toontun** [marrink-lab/vermouth-martinize#392]
Hello, 

I wonder what is the cutoff that will permits to connect two residues in the elastic network (Rubber Band) ? Is it residue i+2 ? i+4? I mean on the linear sequence. 

Thank you,

**Comment by pckroon** [comment]
From: https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/processors/apply_rubber_band.py
There is a minimum distance between residues after which elastic bonds will be applied (default 2, can be overriden with the `-ermd` CLI flag). From the CLI you can also set a minimum and maximum elastic bond length (in nm (or A?)) with `-el` and `-eu`. There is also a minimum forceconstant for elastic bands: if they're weaker than that they'll be removed. You can set that with `-em`. See also `martinize2 -h`, and specifically the Protein elastic network section.

Now, a bit more on the minimum distance between residues: This is /not/ limited to the linear sequence, but will also take e.g. disulphide bonds into account. Note that this behaviour differs from how martinize1 works!

**Comment by toontun** [comment]
OK, very clear, thank you!
