### ISSUE TITLE
martinize2: command not found

### ISSUE THREAD

**Issue by zhouxiandan** [marrink-lab/vermouth-martinize#396]
I have installed vermoutu using :pip install vermouth, but when I use :maetinize2 -h, the terminal return: martinize:command not found.

**Comment by zhouxiandan** [comment]
I don't know how to solve it!

**Comment by pckroon** [comment]
Hello,

what OS are you using? How did you install martinize2? What was the output of the installation? Do you use a virtualenv? 
And please make sure you /copy-and-paste/ the outputs and commands, rather than reproducing them from memory --- a typo is easily made.

**Comment by Tsjerk** [comment]
No follow-up. The pip-install is working. The name of the installed executable is martinize2; probably a typo made. Closing the issue.
