### ISSUE TITLE
Martinize2 can convert an full system to CG?

### ISSUE THREAD

**Issue by georopon** [marrink-lab/vermouth-martinize#400]
Dear, 

I'm missing any thing, it suitable that marinize2  can convert a full system (waters, ions, ligand, protein, membrane) to CG?

or only support proteins?

**Comment by Tsjerk** [comment]
martinize2 can process what is available in the force field and mapping files, except for solvent, where multiple molecules map to a single bead, which is a tough problem. If you have components that are not available yet, you can add them, or ask whether someone else has it or can/cares to add it.

**Comment by georopon** [comment]
Hi Tsjrek,

I have tried to translate the glycosylated and membrane-inserted spyke protein (POPC, POPI, POPS, CHL, POPE) that I have created with charmm-gui, but I had errors where it mentions that it does not recognize the lipid residues, nor the protein residues.

Could you help me on this point, I don't have much experience with CG.

Geo.

**Comment by Tsjerk** [comment]
Hi Geo,

For that conversion, the data for the glycosylation and the lipids needs to be added. We don't have that in yet, as adding building blocks does take some time (our focus with martinize is first on protein/dna). 

For your case, you need to have 1. the charmm descriptions of the lipids and the glycosyl groups (which you should have from the CHARMM-GUI), 2. the coarse grain descriptions for them (which are available for the lipids, and we may have them already for the glycosyl groups, but I'll need to check), and 3. the mappings (which are available for the lipids in Backward, except maybe for POPI). These files should be modified a bit, following the structure of the martinize2/vermouth data files and placed in the corresponding folder under data. Please first have a look there. If you run into trouble, I can help to overcome the problems, but I'm not immediately able to do all this right now.

Hope it helps,

Tsjerk

**Comment by georopon** [comment]
Thanks so much Tsjerk, I will try it that you suggest.

**Comment by pckroon** [comment]
I'll close this issue since there is nothing for us to do with it at the moment. Feel free to reopen it if you need more guidance.
