### ISSUE TITLE
adding dihedral correction using martini beta version appends error message to .itp file.

### ISSUE THREAD

**Issue by majumderS** [marrink-lab/vermouth-martinize#404]
I am following this tutorial: http://cgmartini.nl/index.php/martini-3-tutorials/small-molecule-binding
and I came across this error:
So while adding dihedral corrections to Martini topology using ./bbsc.sh Protein_A.itp 181L.pdb, the resulting .itp file show the following error being appended to the .itp file: 
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
ERROR) BaseMolecule: Cannot bond atom 0 to itself.
moving CA and CB to center of mass of BB, SC1 bead
measuring SC BB BB SC dihedrals
[ dihedrals ]
; SC-BB-BB-SC dihedrals
can't read "rsd": no such variable

On running vmd in my system I get the follwing warnings:
/usr/local/lib/vmd/vmd_LINUXAMD64: /usr/lib/x86_64-linux-gnu/libGL.so.1: no version information available (required by /usr/local/lib/vmd/vmd_LINUXAMD64)

followed by

Info) Multithreading available, 8 CPUs detected.
Info)   CPU features: SSE2 AVX AVX2 FMA 
Info) Free system memory: 1175MB (14%)
Info) No CUDA accelerator devices available.
Warning) Detected X11 'Composite' extension: if incorrect display occurs
Warning) try disabling this X server option.  Most OpenGL drivers
Warning) disable stereoscopic display when 'Composite' is enabled.
Info) OpenGL renderer: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
Info)   Features: STENCIL MSAA(4) MDE CVA MTX NPOT PP PS GLSL(OVFS) 
Info)   Full GLSL rendering mode is available.
Info)   Textures: 2-D (16384x16384), 3-D (512x512x512), Multitexture (8)
Info) Dynamically loaded 2 plugins in directory:
Info) /usr/local/lib/vmd/plugins/LINUXAMD64/molfile

Please help!

**Comment by Tsjerk** [comment]
This is not an issue of vermouth/martinize, but has to do with the script bbsc.sh (which I don't know). Please refer to the martini forum for questions related to the tutorials.
