### ISSUE TITLE
atomnames of edges in modifications limited to 1 character

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#410]
Does anyone know why this check is here? It seems to limit the node atomnames to one character but specifically for modifications. 

https://github.com/marrink-lab/vermouth-martinize/blob/c437876bd494b7842737da48533c44d374fb0526/vermouth/ffinput.py#L968-L970

**Comment by pckroon** [comment]
On 962: `prefixed_atoms.append([prefixed_reference, full_attributes])`. So it's not limited to 1 character. The reason I added that check is because I kept typo-ing atomnames in modification edges, which gives utterly untracable errors. If you don't do this check 972 will add rubbish nodes.

**Comment by fgrunewald** [comment]
@pckroon thanks for the explanation. I see what's happening there. This is also what allows parsing of node attributes via the edges section.
