### ISSUE TITLE
parameterisation of protonated aspartate (ASH) and histidine (HIE)

### ISSUE THREAD

**Issue by athar91** [marrink-lab/vermouth-martinize#412]
I have experiementally verified protonated amino acids in my protein and martinize2 is giving error for ASH and HIE residues. Do martinize2 have parameterization of protonated states of ASH and HIE, if yes what is the nomenclature. If no, how do we insert parameterization of ASH and HIE?

thanks

**Comment by fgrunewald** [comment]
@athar91 we're currently working on the protonated AAs. as far as I know the neutral AA definitions are not available yet in martinize2

**Comment by fgrunewald** [comment]
the data has been made available
