### ISSUE TITLE
mapping for nucleobases

### ISSUE THREAD

**Issue by supremesquishy** [marrink-lab/vermouth-martinize#420]
Hello Martinize2-Developer Team,

I want to parametrize a small molecule GDP in a consistent manner with the martini3 ff. 
There is a topology file for nucleobases martini_v3.0.0_nucleobases_v1.itp but I can't find anywhere mappings for them.

Are they somewhere available? If not is it possible that you can share them with me?

Thank you in advance.

**Comment by fgrunewald** [comment]
Hi @supremesquishy, 

Nucelobase parameters and mappings remain unpublished for the time being. Therefore we cannot distribute or provide mapping parameters for the nucleobases or DNA via martinize2. You will need to file a request with the corresponding author(s) of the Martini3 paper. We are aware that this is a less than ideal situation, however, as martinize2 developers our hands are tied in this regard. 

Cheers,
Fabian
