### ISSUE TITLE
DoMapping transfer to many attributes

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#45]
When doing the mapping, and when mapping multiple atoms from the initial system to a target particle, we transfer all the attribute of the last selected atom from the initial system to the target particle, but the position. This means that some attribute that make no sense for the target are transfer. This means we can have a Martini side chain tagged with hydrogen as its element.

One fix would be to transfer only the attributes that have the same value in all the selected atoms. We can have a blacklist of attributes we know should not be transferred, in order to save some comparison time.

**Comment by pckroon** [comment]
Since this was opened the do_mapping processor has been completely overhauled. So is this still relevant?

**Comment by jbarnoud** [comment]
I need to check, but we may be transferring not enough attributes now...
