### ISSUE TITLE
Proponation modifications mappings can't be found

### ISSUE THREAD

**Issue by WangLiguo-kyrie** [marrink-lab/vermouth-martinize#451]
As in example
`martinize2 -f 1N6T.pdb -o NKA.top -x NKA_cg.pdb -dssp dssp`

atom HD2 in ASP4 was identified as modification [ASP0], but there is unmap warning:
_WARNING - unmapped-atom - Can't find modification mappings for the modifications ['ASP0']._ 

Besides, the HD1 in HIS1(modification HSD) wasn't identified.

--version martinize with vermouth 0.7.3

**Comment by WangLiguo-kyrie** [comment]
I changed the ASP4 in 1N6T to ASPP format (neutral state in CHARMM naming format):
ATOM     53  N   ASPPA   4       5.805   0.387   1.403  1.00  0.00           N  
ATOM     54  CA  ASPPA   4       5.561   0.072   2.800  1.00  0.00           C  
ATOM     55  C   ASPPA   4       6.009  -1.364   3.081  1.00  0.00           C  
ATOM     56  O   ASPPA   4       6.236  -1.733   4.232  1.00  0.00           O  
ATOM     57  CB  ASPPA   4       4.073   0.178   3.137  1.00  0.00           C  
ATOM     58  CG  ASPPA   4       3.660   1.471   3.844  1.00  0.00           C  
ATOM     59  OD1 ASPPA   4       4.335   2.504   3.730  1.00  0.00           O  
ATOM     60  OD2 ASPPA   4       2.580   1.388   4.545  1.00  0.00           O  
ATOM     61  H   ASPPA   4       5.015   0.275   0.800  1.00  0.00           H  
ATOM     62  HA  ASPPA   4       6.137   0.806   3.364  1.00  0.00           H  
ATOM     63  HB2 ASPPA   4       3.499   0.086   2.215  1.00  0.00           H  
ATOM     64  HB3 ASPPA   4       3.798  -0.667   3.768  1.00  0.00           H  
ATOM     65  HD2 ASPPA   4       2.509   0.480   4.958  1.00  0.00           H  

and as in example
`martinize2 -f 1n6t-pro.pdb -x 1n6t_cg-pro.pdb -o 1n6t-pro.top -ff martini22 `
warning still existed:
**_WARNING - unmapped-atom - These atoms are not covered by a mapping. Either your mappings don't describe all atoms (bad idea), or, there's no mapping available for all residues. ['53A-ASPP4:N', '54A-ASPP4:CA', '55A-ASPP4:C', '56A-ASPP4:O', '57A-ASPP4:CB', '58A-ASPP4:CG', '59A-ASPP4:OD1', '60A-ASPP4:OD2']_**
set `-maxwarn 1`, the result itp file would lack ASPP4 residue

**Comment by WangLiguo-kyrie** [comment]
Sorry, I didn't realize that "**The current development version doe**s"
Does the current development version mean not yet released?

**Comment by fgrunewald** [comment]
The current version means the GitHub development version. So you need to install Martinez from GitHub and it will only work for Martini3 proteins at the moment. I didn't realise you were using martini22

**Comment by WangLiguo-kyrie** [comment]
I'm using martini3, using martini22 in example was just to stay the same with the force field in tutorial.

I fould the protonation naming in newest martini3 aminoacids.ff and blocks of Universal force field were same(like ASPP), yet the protonation block naming was different (like ASP0). Is this the reason why this development version only work for Martini3 proteins at the moment?

**Comment by WangLiguo-kyrie** [comment]
I tried the developemnt version.
It works. ASPP LSN could be identified and mapped correctly.
Thank you!

**Comment by fgrunewald** [comment]
You're welcome! 😄
