### ISSUE TITLE
Rubberband bond type is 1 instead of 6 in topology file

### ISSUE THREAD

**Issue by compchemeric** [marrink-lab/vermouth-martinize#452]
Dear all,

martinize2 writes the rubber bands as type 1 GROMACS bonds in to the itp files. It should be type 6, however. I guess it has to do with how the rubberband routine detects the bond type as the type of actual chemical bonds in the force field (type 1). Mathematically it is identical, but e.g. the cg_bonds.tcl scripts affords the description as "HARMONIC" in the tpr dump to correctly draw the rubber bands. 

The default bond type is actually set to 6 in the rubberband file, however in my case it always ends up as 1.

Best, 
Eric

**Comment by fgrunewald** [comment]
Hi Eric, 

Which Martini force-field are you talking about? For Martini3 the EN bond-type should be 1 not 6 as in the previous Martini models. They are also not identical bond-types. With number 1 the non-bonded interactions are excluded between the bonded beads whereas they are not with type 6. The change to type 1 was deliberate in Martini3. The `cg_bonds.tcl` may not have kept up with that, but that's not a martinize2 issue really. In case you were talking about another Martini version we can go and investigate what is going on. 

Cheers,
Fabian

**Comment by compchemeric** [comment]
Hi Fabian,

thanks for the quick replay. I have just started with Martini3, so the question was related to this version. I now understand that Martini3 uses type 1 bonds instead of type 6. (And of course, they differently affect the non-bonded interactions) I must have overseen this change in the Martini3 papers and supplementary informations. Sorry for coming up with the issue, then. Thanks for sorting it out.  

Clearly, cg_bonds.tcl is not of concern for this repo, however a demand for a visualization of the elastic network remains. Replacing the bond type in the itp from 1 to 6 only for visualisation and modeling purposes is at least a workaround. 

Thanks again and all the best,
Eric

**Comment by fgrunewald** [comment]
Hey Eric, 

Nothing to be sorry about! We are happy to answer these questions. In particular, you raising this issue on GitHub means other people with the same question are now able to find the answer more quickly. 

I also understand the need for visualisation tools that are able to show elastic network bonds. We are aware of the issue and it is on the list of things to be fixed. Unfortunately, it is up there with quite a few other things and VMD is not always the kindest program when it comes to development of scripts. I'll ping you when we have an updated version, but for now I'm going to close the issue. 

Cheers,
Fabian
