### ISSUE TITLE
Eunit flag Broken

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#459]
Someone messed up when implementing #422. The lines below are actually non-sense because they overwrite the e-unit criterion. 

https://github.com/marrink-lab/vermouth-martinize/blob/aa53b3e3ca734032518bd56b3b8dad0831653612/bin/martinize2#L737-L741

**Comment by fgrunewald** [comment]
@pckroon I'd prefer we get rid of one of the flags either `rb_region` or `rb_unit` and for the reminaing flag we accepts either the keywords `chain`, `molecule`, `all` or a resid region

**Comment by fgrunewald** [comment]
well the rb_region flag already takes both keywords and also resid lists at the moment

**Comment by fgrunewald** [comment]
@pckroon This is actually a bit more complicated than I thought: What should happen when we have one molecule consisting of two chains and define a resid region? Should the EN be formed between the chains or not?

**Comment by pckroon** [comment]
Logically all criteria should get ANDed. For now though, the CLI is limited to providing just a single criterion (right?). So yes, it should be formed between the chains.
