### ISSUE TITLE
problem during backmapping

### ISSUE THREAD

**Issue by mmidhun97** [marrink-lab/vermouth-martinize#466]
Dear sir when im backmapping the protein using gromacs im getting the following problem.

Fatal error:
Incomplete ring in HIS8

could you please help

Regards,
Midhun Anila
Research scholar
Laboratory of Biophysics SL-4
institute of physics
polish academy of sciences
Warsaw

**Comment by pckroon** [comment]
Hi,
martinize2 does not deal with backmapping. Martinize2 converts structures from AA to CG.
