### ISSUE TITLE
-nt flag not producing expected result

### ISSUE THREAD

**Issue by csbrasnett** [marrink-lab/vermouth-martinize#487]
I can see this might be related to #472, but I'm not 100% sure so am opening a separate issue. 

From the aminoacids.ff file for martini, I would expect the following section regarding protein termini to make the N terminus (BB -BB) a P5 bead, and C terminus (BB +BB) a P6 bead:

```
[ link ]
[ molmeta ]
neutral_termini true
[ atoms ]
BB {"replace": {"atype": "P5"}}
[ non-edges ]
BB -BB

[ link ]
[ molmeta ]
neutral_termini true
[ features ]
neutral_termini
[ atoms ]
BB {"replace": {"atype": "P6"}}
[ non-edges ]
BB +BB
```

However, if I run martinize2 with -nt, the result is that _both_ BBs are of type P6.

**Comment by pckroon** [comment]
Termini parameters are defined as modifications (the link hacks you found are from a previous era ;) ). You can find them (for martini3001) in https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/data/force_fields/martini3001/modifications.ff. The `-nt` flag is hardcoded to apply the modifications 'COOH-ter' and 'NH2-ter' (https://github.com/marrink-lab/vermouth-martinize/blob/master/bin/martinize2#L606).
Make sure you're running a version of martinize in which #476 and #477 have been merged.

**Comment by csbrasnett** [comment]
Thanks for the clarification, can see that now!
