### ISSUE TITLE
elnedyn along with martini3 

### ISSUE THREAD

**Issue by dim-99** [marrink-lab/vermouth-martinize#497]
Hi,

Is it possible to use elnedyn along with martini3 ? the only option I see when using martinize2 is elnedyn22, elnedyn22p and elnedyn. 

Thank you,

Best,
Dimuthu

**Comment by fgrunewald** [comment]
Hi, 

The Martini 3 protein model was not optimised in relation with Elnedyn. So it is not available a an option. Alternatively, we recommend using a Go-like model for more accurate flexibility, if the usual elastic network does not work for you. 

Cheers,
Fabian

**Comment by dim-99** [comment]
Thanks !
