### ISSUE TITLE
Mapping structure

### ISSUE THREAD

**Issue by pckroon** [marrink-lab/vermouth-martinize#5]
Mappings are currently a hardcoded dragon. This should probably some sort of class, and the data be read from a file. It should probably be (part of) a ForceField.

**Comment by pckroon** [comment]
Referencing #17, since that also deals with coordinate generation

**Comment by jbarnoud** [comment]
Can this be closed? We read the mapping from file and place the beads. There are some improvements needed, indeed: the mapping format does not allow to cross residues yet, missing coordinates are not built. But these are beyond the base feature.

I close. Feel free to reopen.
