### ISSUE TITLE
 WARNING - unmapped-atom - Can't find modification mappings for the modifications ['HSD', 'N-ter'].

### ISSUE THREAD

**Issue by wangwestlake** [marrink-lab/vermouth-martinize#504]
I tried the martinize2 with the Vermouth version of 0.9.1, it produced this error! Any suggestion is highly appreciated.
[m3filesdebug.zip](https://github.com/marrink-lab/vermouth-martinize/files/10802840/m3filesdebug.zip)

**Comment by pckroon** [comment]
Hi,

I'm pretty sure I've had to squash this bug three or five time now...

I'm  a little surprised you pass -ff-dir and -map-dir; do those differ from the data files on the master branch? In addition, what is your N-terminal residue? What's the output of `martinize2 -vv` regarding that residue?

**Comment by fgrunewald** [comment]
@wangwestlake were you able to solve the issue?

**Comment by wangwestlake** [comment]
Hi all,

Thanks much for the reply. The problem have been solved, if I do not specify the directory of ff and map, since the mapping files in my directory are in older versions!

Best,
Jiaqi

**Comment by wangwestlake** [comment]
> @wangwestlake were you able to solve the issue?
