### ISSUE TITLE
No module named 'core'

### ISSUE THREAD

**Issue by Clare-xiong** [marrink-lab/vermouth-martinize#508]
I'm trying to follow the procedure from the following website: http://cgmartini.nl/index.php/martini-3-tutorials/small-molecule-binding#1A. , with the command line being:

./martinize -f 181L.pdb -ff martini303v.partition -x CG.pdb -o topol.top -dssp dssp -elastic

And the output I got this:

Traceback (most recent call last):
  File "D:\program\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\program\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".\martinize\__main__.py", line 3, in <module>
  File ".\martinize\martinize\__init__.py", line 37, in <module>
ModuleNotFoundError: No module named 'core'

I was wondering if anyone could give me some pointers with this?

**Comment by pckroon** [comment]
You're not running martinize2, so this is the wrong place for this error.

**Comment by Clare-xiong** [comment]
> You're not running martinize2, so this is the wrong place for this error.

When I run the martinize2, it says ValueError: Unknown force field "martini303v.partition".
The command is martinize2 -f 5oqv.pdb -ff martini303v.partition -x CG.pdb -o topol.top -dssp dssp -elastic
