### ISSUE TITLE
Pytest CodeCov failure

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#513]
It appears pytest with code coverage isn't installing properly anymore ... @pckroon am I missing something?

**Comment by pckroon** [comment]
You mean https://github.com/marrink-lab/vermouth-martinize/actions/runs/4491130106/jobs/8306409892? 
Seems the python codecov package is deprecated. See https://github.com/codecov/example-python/blob/main/.github/workflows/ci.yml for the new way to do this.
