### ISSUE TITLE
Go Virtual Sites in incorrect order

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#519]
It appears the sorting of particles taking place at the end of the martinize2 pipline messes with the Go virtual site script because the VS get sorted to the specific residues. What we should do is implement the full Go pipline into martinize2. As a quick-fix we can add an if wrapper around the sorting statement.

**Comment by pckroon** [comment]
Is this a duplicate of #518? Or just related misery?

I'm OK with either a) implement Go properly; b) Quick-fix as you suggest; c) remove everything Go related until someone implements option a.

**Comment by fgrunewald** [comment]
not quite the same but related, you cannot fix one without the other. Let's try option b) and on Thursday I can see if I can find someone to do this properly

**Comment by fgrunewald** [comment]
the issue should be solved now
