### ISSUE TITLE
Building Docs Fails

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#540]
Apparently the docs building fails because in py 3.10 quotient_grpah is not found. See latest actions run. @pckroon any ideas why? As far as I can the latest version still has the quotient_graph. ...

**Comment by pckroon** [comment]
Nothing obvious.
```
Collecting networkx~=2.0 (from vermouth==0.9.4)
  Downloading networkx-2.8.8-py3-none-any.whl (2.0 MB)
```
Is there a reason we're using networkx 2.x rather than latest? (3.1)

**Comment by fgrunewald** [comment]
@pckroon good to know! I'll bump the version requirement and investigate

**Comment by fgrunewald** [comment]
for some reason that I really grow to hate building docs still fails in the deploy stage

**Comment by pckroon** [comment]
0.9.4 does not contain the change from #542

**Comment by fgrunewald** [comment]
@pckroon can you mint a new release to see if this is resolved?

**Comment by pckroon** [comment]
Works!
