### ISSUE TITLE
some error about dssp

### ISSUE THREAD

**Issue by bdx114514** [marrink-lab/vermouth-martinize#562]
Hello,

I use 
"martinize2 -f B2A31.pdb -x B2A3_CG.pdb -ss B2A31.dssp -ff martini3001 -o topol.top"
to generate CG  and top file, but it shows the following error:
**ValueError: The length of the sequence (10) does not match the number of residues in the selection (180).**

If I change to use 
"martinize2 -f B2A31.pdb -x B2A3_CG.pdb -dssp mkdssp -ff martini3001 -o topol.top ",
It shows:
**Error trying to load file "/home/yancong/Desktop/MD11_26/dssp_in_670i2c0g.pdb"
Expected record CRYST1 but found ATOM  
. The input file provided to DSSP can be found at /home/yancong/Desktop/MD11_26/dssp_in_670i2c0g.pdb.**
It seems that there is a temporary file named dssp_in_670i2c0g.pdb that has not been generated correctly, and a line “CRYST1” is missing
[files.zip](https://github.com/marrink-lab/vermouth-martinize/files/13466318/files.zip)
I have uploaded all the relevant files.

**Comment by pckroon** [comment]
Hellohello,

which version of martinize2 are you using? Which version of dssp are you using? We're unfortunately limited to versions (if memory serves) 2 and 3. 
You can try the branch from PR #547, which uses dssp from the mdtraj library

**Comment by bdx114514** [comment]
> Reference in

I used the latest version of DSSP (4.0) before, but now I switched to an older version (3.0.10), and there are no errors now. Thanks!
