### ISSUE TITLE
How to deal with the different protonation states in martinize2?

### ISSUE THREAD

**Issue by yuqingxiong96** [marrink-lab/vermouth-martinize#564]
I check the protonations state of the acidic and basic amino acids using the protein plus server. And the predictions of the protonation state for Asp1 is (-NH), and the original state is -NH4+. I use the two pdb file with different protonation state for Asp on the martinize2. The out put molecule_0.itp files for the Asp1 are the same. It seem changes in the protonation states are still not part of martinize2. How to change the protonation of residues in the molecule_0.itp file?

**Comment by pckroon** [comment]
Alternatively, for example if your PDB file has no resolve hydrogens, you can do (e.g.) `martinize2 -modify ASP42:ASP-HD2` to protonate ASP42. The modifications are defined here: https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/data/force_fields/charmm/modifications.ff#L101, and the final effect they have on the martini3 topology here: https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/data/force_fields/martini3001/modifications.ff
