### ISSUE TITLE
BB-BB(-1)-BB(+1)-SC improper dihedral definition

### ISSUE THREAD

**Issue by WangLiguo-kyrie** [marrink-lab/vermouth-martinize#569]
I define an BB-BB(-1)-BB(+1)-SC improper dihedral in martini3 force field, there is no warning in Martinize2 execution, but this definition is not applied in generated itp file.

This is the definition of BB-BB(-1)-BB(+1)-SC improper dihedral:
```
[ link ]
[ atoms ]
 BB {"resname": "PRO"}
-BB {"resname": $protein_resnames}
+BB {"resname": $protein_resnames}
SC1 {"resname": "PRO"}
[ dihedrals ]
BB -BB +BB SC1 2 -10 80 {"group": "BB-BB(-1)-BB(+1)-SC improper"}
[ edges ]
BB -BB
+BB SC1
```

**Comment by pckroon** [comment]
I think you're missing the edge `BB +BB`
@fgrunewald do you know by heart whether dihedral definitions add edges?

**Comment by fgrunewald** [comment]
@pckroon they don't add edges; so if the edges are incorrect then it wouldn't work

**Comment by pckroon** [comment]
Right, missed something. You shouldn't have an edge between SC1 and +BB, but between SC1 and BB instead. So your edges become:

```
[edges]
BB +BB
BB -BB
BB SC1
```

**Comment by WangLiguo-kyrie** [comment]
Got it!
It works. Thank you!
