### ISSUE TITLE
Lazy merging?

### ISSUE THREAD

**Issue by csbrasnett** [marrink-lab/vermouth-martinize#587]
If I have a protein complex with many chains and just want a single merged itp out, the current input is slightly annoying in having to make list of all of them (although, I often think this of even something with 2 chains... more of a reflection on me than anything else...) 

Is there any reason in principle implementing something like `-merge all` is a bad idea? Happy to do the PR myself but just wanted to check if this has been discussed and rejected before!

**Comment by pckroon** [comment]
By all means go ahead, I think it's a fine feature :)
I can't think of any reason why this would be a particularly bad idea.
