### ISSUE TITLE
order of [ bond ], [ angle ], [ dihedrals ] itp directives not consistent

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/vermouth-martinize#59]
Running the same martinize2 command for a united-atom topology multiple times I could obtain all possible order combinations of the `[ bonds ]`, `[ angles ]`, and `[ dihedrals ]` directives in the output itp file. This hints to current random printing of the various GROMACS itp sections. Note that `[ moleculetype ]` and `[ atoms ]` *always* appear in the correct order (i.e., 1st and 2nd, respectively). 

This of course does not affect the quality of the topology but may be important to have a consistent printing order for the itp sections.

**Comment by jbarnoud** [comment]
A way to fix this would be to have a preferred ordered for the interactions in the ITP writer.

**Comment by Tsjerk** [comment]
The preferred order is:

atoms
pairs
bonds
angles
dihedrals
rest...

**Comment by pckroon** [comment]
My suggestion is to sort it by 1) the number of atoms involved in the interaction, and 2) alphabetically. That would result in something like this:
 - atoms
 - exclusions
 - bonds
 - constraints
 - pairs
 - angles
 - dihedrals

Not quite perfect maybe, but it makes sense, and it prevents all hardcoding of section names.
