### ISSUE TITLE
User input

### ISSUE THREAD

**Issue by pckroon** [marrink-lab/vermouth-martinize#6]
There is no option for user input, other than hardcoded paths.

**Comment by jbarnoud** [comment]
From the list above, the options that are still missing are:
* `-his`
* `-link`
* `-name`
* Multiscaling

**Comment by pckroon** [comment]
Status?

**Comment by jbarnoud** [comment]
From the options in the list just above, only `-cys` was added.

**Comment by fgrunewald** [comment]
this seems like a stale issue. If specific CLI flags are still missing I'd suggest opening a specific issue for each.
