### ISSUE TITLE
-govs-include no longer present?

### ISSUE THREAD

**Issue by BartBruininks** [marrink-lab/vermouth-martinize#603]
Dear martinizers,

We have been working on an alternative Go implementation and it is currently in publication, however, when I try to run our scripts with the current Martinize2 it seems the -govs-include flag does not exist anymore. We have a custom script that allows for arbitrary copy numbers for homooligomers. Is there a suggested workaround or are we now stuck at an older version (if so, which one?). It would be nice if the old behavior would still be supported.

**PREVIOUSLY WORKING COMMAND:**
martinize2 -f protein.pdb -o output.top -x protein_cg.pdb -dssp /path/to/dssp -p backbone -ff martini3001 -govs-include -govs-moltype protein_name -scfix

**Comment by pckroon** [comment]
`-govs-include` has been superseded by `-go`, with changed semantics in #550. The previous flag will not be restored.
I strongly suggest adapting your new model to the new flags, since it'll be better for your sanity.

**Comment by BartBruininks** [comment]
Yhea I was on the same track.
