### ISSUE TITLE
Issue with dssp file and pdb file:The length of the sequence (15) does not match the number of residues in the selection (16)

### ISSUE THREAD

**Issue by Musna98** [marrink-lab/vermouth-martinize#614]
**I'm trying to build a course grained structure of penetratin using martinize.I get this error:**
martinize2 -f penetratin.pdb -o single-protein.top -x penetratinCG3.pdb -ss penetratin.dssp -ff martini3001 -p backbone 
    INFO - general - Read 1 molecules from PDB file penetratin.pdb
    INFO - step - Guessing the bonds.
    INFO - general - 1 molecules after guessing bonds
    INFO - step - Repairing the graph.
    INFO - general - Applying modification N-ter to residue A-ARG1
    INFO - general - Applying modification C-ter to residue A-LYS16
    INFO - step - Dealing with modifications.
    INFO - general - Identified the modifications ['N-ter'] on residues ['ARG1', 'ARG1', 'ARG1', 'ARG1']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS4']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS13']
    INFO - general - Identified the modifications ['LYS-HZ3'] on residues ['LYS15']
    INFO - general - Identified the modifications ['C-ter'] on residues ['LYS16', 'LYS16', 'LYS16']
    INFO - step - Read input.
Traceback (most recent call last):
  File "/home/musna/miniconda3/bin/martinize2", line 1114, in <module>
    entry()
  File "/home/musna/miniconda3/bin/martinize2", line 885, in entry
    ).run_system(system)
      ^^^^^^^^^^^^^^^^^^
  File "/home/musna/miniconda3/lib/python3.12/site-packages/vermouth/dssp/dssp.py", line 643, in run_system
    raise ValueError(
**ValueError: The length of the sequence (15) does not match the number of residues in the selection (16).**

The pdb file and dssp files show 16 residues,but still im having this problem.Please help me with this.

**Comment by pckroon** [comment]
The `-ss` flag does not accept a dssp output file as argument, but rather the sequence of assigned secondary structures. Please see the following issues/discussions:
https://github.com/marrink-lab/vermouth-martinize/issues/613
https://github.com/orgs/Martini-Force-Field-Initiative/discussions/5

**Comment by Musna98** [comment]
I realized that Note that martinize2 only works with the dssp versions 3.1.4 or older, because the output changed in the latest dssp version 4. So, I tried providing the required secondary structure from STRIDE and fed it to the script and I was able to do it. Thank you all!

**Comment by fgrunewald** [comment]
Thanks for getting back to us and glad it worked.
