### ISSUE TITLE
-go-moltype arguement not used

### ISSUE THREAD

**Issue by chenyuwai** [marrink-lab/vermouth-martinize#627]
Dear all,

It seems like the value entered after "-go-moltype" is not respected. Instead, the default "molecule_0" is always used in the generated .itp and .top files.

I am using:
martinize with vermouth 0.11.0 (by martinize2 -V)
lately installed by "pip install vermouth" in a Python 3.8 environment.

Thanks.

**Comment by pckroon** [comment]
Thanks. This should get fixed by #623. @csbrasnett could you double check it does?

**Comment by chenyuwai** [comment]
Thank you both for the responses. I am just a newbie learning go-martini. I think it might worth keeping -go-moltype because the next step after martinize2 is to run the create_goVirt.py script, where there is an arguement --moltype to specify exactly the same name.

**Comment by csbrasnett** [comment]
no problem, @chenyuwai if you're using version 0.11.0, the create_goVirt.py script isn't actually necessary any longer for your go model. you should be able to martinize your protein complete with something like:

`martinize2 -f input.pdb -x out.pdb -o topol.top -go contact_map.out -cys auto -scfix`

where `contact_map.out` is the one obtained from the Go model server beforehand: http://pomalab.ippt.pan.pl/GoContactMap/

**Comment by chenyuwai** [comment]
Thanks. That is great to know---I'll give it a go later. It is much simplified. So, I think I can declare this issue closed.
