### ISSUE TITLE
this is a problem about martinize2 can't run.

### ISSUE THREAD

**Issue by chemcrazy** [marrink-lab/vermouth-martinize#633]
When I have installed martinize2,  and run "Martinize2 -h", The following situation occurred:"
 File "/home/chemcrazy/.local/bin/martinize2", line 1100
    LOGGER.log(loglevel, entry, **fmt_arg, type="model")
                                         ^
SyntaxError: invalid syntax",   please tell me how to resolve it. thank you.

**Comment by pckroon** [comment]
Which version of python are you running? How did you install martinize2? Which OS?

**Comment by chemcrazy** [comment]
The OS is Ubuntu18.04.6 LTS
The version of python is 3.6.9,  I installed the martinixe2 according the website "marrink-lab/vermouth-martinize: Describe and apply transformation on molecular structures and topologies", first: pip install vermouth, 
second:pip install git+https://github.com/marrink-lab/vermouth-martinize.git#vermouth, 
and then: martinize2 -h    after that it showed "File "/home/chemcrazy/.local/bin/martinize2", line 1116
    LOGGER.log(loglevel, entry, **fmt_arg, type="model")
                                         ^
SyntaxError: invalid syntax"


    thank you very much.


| |
陈超
|
|
***@***.***
|
---- Replied Message ----
| From | Peter C ***@***.***> |
| Date | 11/15/2024 21:08 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [marrink-lab/vermouth-martinize] this is a problem about martinize2 can't run. (Issue #633) |

Which version of python are you running? How did you install martinize2? Which OS?

**Comment by pckroon** [comment]
Ubuntu 18 and python 3.6 are ancient. Martinize2 requires python 3.9 or higher. I just spotted that the readme is out of date.
You can install the latest released version with `pip install vermouth`. The second invocation you put is only to install the development version.

**Comment by chemcrazy** [comment]
Thank you very much for your prompt reply. I will try it according to your suggestion.


                  best wishes 


| |
陈超
|
|
***@***.***
|
---- Replied Message ----
| From | Peter C ***@***.***> |
| Date | 11/15/2024 21:32 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [marrink-lab/vermouth-martinize] this is a problem about martinize2 can't run. (Issue #633) |

Ubuntu 18 and python 3.6 are ancient. Martinize2 requires python 3.9 or higher. I just spotted that the readme is out of date.
You can install the latest released version with pip install vermouth. The second invocation you put is only to install the development version.
