### ISSUE TITLE
Top file include itp duplicate in grompp?

### ISSUE THREAD

**Issue by Vini161** [marrink-lab/vermouth-martinize#636]
Should the topol files also have: 
```
#define GO_VIRT
#include "martini.itp".     <using martini_v3.0.0.itp>
 #include "go_atomtypes.itp"
 #include "go_nbparams.itp"
#include "molecule_0.itp"
```

Because I get warning in grompp (gmx 2021) that atoms Atomtype was defined previously, removing them 
 
```
#define GO_VIRT
#include "martini.itp"
#include "molecule_0.itp"
```

seems to resolve the issue. Is this fine?

Note that i have added
```
#ifdef GO_VIRT
#include "go_atomtypes.itp"
#endif
```
and
```
#ifdef GO_VIRT
#include "go_nbparams.itp"
#endif
```

in my martini.itp

**Comment by csbrasnett** [comment]
yes, this is what I raised in #624, I'll sort a fix asap
