### ISSUE TITLE
Webserver issue in getting contact map of pdb

### ISSUE THREAD

**Issue by Vini161** [marrink-lab/vermouth-martinize#640]
I have a hexamer protein, I am trying to get contact map from webserver, 
<img width="1013" alt="Screenshot 2024-11-25 at 1 44 43 PM" src="https://github.com/user-attachments/assets/db3f8ffe-0efd-4ee6-98f0-1a9136daf12a">
 I get the above error. 
I have attached my pdb file
[mer6_sym_clean.pdb.zip](https://github.com/user-attachments/files/17899614/mer6_sym_clean.pdb.zip)

**Comment by pckroon** [comment]
This is not a martinize2 error, can't help you with that I'm afraid.
