### ISSUE TITLE
Coarse Graining Proteins from Charmm-Gui

### ISSUE THREAD

**Issue by zamydm** [marrink-lab/vermouth-martinize#645]
Good Morrow.

I have been attempting to coarse grain a small selection of proteins that I have repaired using the modeler functionality available in Charmm-Gui. However, in every attempt to coarse grain them through martinize, I have failed. I believe a large reason for that is that I am coming to realize I am rather inexperienced in this area as my focus has always been in larger simulations.

Regardless, I was hoping to request assistance in choosing appropriate flags for a protein generated from Charmm-Gui to ensure the program runs smoothly. More information:
- The program in its base form reaches the following step before terminating early with no given error message: INFO - general - Applying modification N-ter to residue P-ARG110. I believe this may be due to it attempting to add a N-ter residue where one already exists, though I could be wrong in that observation.
- The output .pdb from Charmm-Gui has many atoms with the same name. While this shouldn't be a problem, I would like to still make note of it as this generates hundreds of warnings in martinize.
- There are no missing residues from the Charmm-Gui protein. All necessary n-ter and c-ter modifications have been made.
- Using Charmm-Gui's direct martini-maker functionality is not an option as the developers have made the oversight of including the .itp files for the proteins, meaning using insane afterwards becomes impossible.
- I have attempted to use tutorials provided at https://github.com/marrink-lab/martinize-examples for assistance as well as the selection directly from the martini website, and yet have had issues proceeding further.

I hope I am not asking too much for assistance here, I am just trying to better understand how to use martinize. Thanks in advance.

**Comment by pckroon** [comment]
Hello hello!
That doesn't sound like desirable martinize2 behaviour ;)
- Which version of martinize2 are you running?
- Are you capable of martinizing other proteins/systems? For example 1UBQ?
- Does `martinize2 -v` say anything intelligent? It usually produces a lot of output that needs some digesting.
- Any chance you could share the atomistic PDB with us here?

**Comment by zamydm** [comment]
Thanks for the fast response! Regarding your questions:
- I am using version 0.12.0
- I have used the software to attempt to martinize the proteins TRPV1 and Slo2.2; both failed in a similar fashion.
- Finally, for the last two points, I am not in my office yet. When I get there I can share more information.

**Comment by zamydm** [comment]
Sorry for the wait. The error produced by Martinize2 for Slo2.2 is as follows: 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/martinize2", line 1164, in <module>
    entry()
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/martinize2", line 836, in entry
    file_extension = args.inpath.suffix.upper()[1:]  # We do not keep the dot
                     ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'suffix'

The area where the program failed was at:

<img width="888" alt="Screenshot 2024-12-20 at 12 02 38" src="https://github.com/user-attachments/assets/e9d8caae-a698-4c4a-b89d-9b68ccd9b4b8" />

The error produced for TRPV1 is as follows: 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/martinize2", line 1164, in <module>
    entry()
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/martinize2", line 836, in entry
    file_extension = args.inpath.suffix.upper()[1:]  # We do not keep the dot
                     ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'suffix'

The area where the program failed was at:

<img width="888" alt="Screenshot 2024-12-20 at 12 16 17" src="https://github.com/user-attachments/assets/e2005c0c-3afa-4072-a5af-9cab7dc4f618" />

As far as sharing the protein structures, I would prefer not to if at all possible. I additionally tested the suggested protein 1UBQ. I was able to get it working and get a decent result, however when I tried to run it with -dssp I got the error: vermouth.dssp.dssp.DSSPError: Failed to get DSSP version information.

Again, I believe the issue I am facing is likely one of me improperly using the software and not having the right flags enabled. The proteins are very large (they are full ion channels) and are saved as .pdbs in the Charmm36 format.

**Comment by csbrasnett** [comment]
hey @zamydm can you upload the pdb you're using/send it to me, and specify what martinize2 command you're using in full? I'll try to help asap if you can

**Comment by zamydm** [comment]
Sure, do you have a preferred method of contact?

**Comment by csbrasnett** [comment]
@zamydm if you do a folder on google drive/whatever and link to it here that's fine, or my email's listed on [this page](https://www.rug.nl/research/molecular-dynamics/people/groupmembers)

**Comment by zamydm** [comment]
An update on what worked for me. I instead used the inbuilt chain repair tool in ChimeraX which is powered by modeller. This addressed the issue with protein construction. I then for atomistic simulations fed this repaired protein into Charmm-Gui for membrane construction. In essence, avoid using Charmm-Gui for repairing proteins if you plan to use the proteins in a coarse grained matter.

**Comment by pckroon** [comment]
Thanks for getting back with the update. I'll add my own insights here, for posterity.

`AttributeError: 'NoneType' object has no attribute 'suffix'` can be fixed by providing the `-x` and `-o` flags. Those defaults should probably be changed...

In the images you posted, the warnings are rather telling. The formatting/structuring of your atomistic pdb is highly suspect. As for your issues with charmm-gui, martinize2 is rather picky about coordinates.
