### ISSUE TITLE
Gracefully ignore unknown ligands

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#74]
Martinize 1 ignores HETATM records. As a consequence, it ignores all ligands. As most users only care about the proteins, it is the expected behavior. For now, martinize 2 ignores the full molecule where there is an unknown residue. This works as long as the ligand is not close enough to have an edge connecting it with the protein.

What would be the best strategy to ignore unknown ligands while keeping as much information as possible?

**Comment by fgrunewald** [comment]
we now have an ignore flag. I'd say that's for the time being good enough. If not pleas reopen.
