### ISSUE TITLE
The autogenerated AUTHORS and CHENGELOG files are unusable

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#79]
The list of authors and the changelog that pbr generate automatically are nonsensical. @pckroon appears 4 times in `AUTHORS` with different email addresses, @Tsjerk appears twice. The changelog is based only on the commit titles and we are not tidy enough for that.

There is an option in PBR to deactivate the generation of these files, but it means we'll have to maintain these files ourselves.

**Comment by pckroon** [comment]
> There is an option in PBR to deactivate the generation of these files, but it means we'll have to maintain these files ourselves.

That works for me.

**Comment by pckroon** [comment]
Is this still an issue?

**Comment by jbarnoud** [comment]
Looks OK now.
