### ISSUE TITLE
Martinize2 should be able to specify individual cys bridges

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#84]
Martinize 1 can use the -cys option to specify individual cystein bridges. Martinize 2 needs the same feature. The same code can also be used to setup arbitrary edges.

**Comment by fgrunewald** [comment]
Technically it should be possible by using CYS auto and make bonds from connect records only and then omit the connect records for the CYS bridges one wants to omit. However, it seems the need for this procedure is very low.
