### ISSUE TITLE
Automatic indexer

### ISSUE THREAD

**Issue by ifaust83** [marrink-lab/vermouth-martinize#95]
Hi, 
This is more a request. When parametrising a new molecule one has to create an index file to 'coarse-grain' the atomistic trajectory. So it would be helpful to have a way to automatically create this index for any molecule (if this is possible). I am planning to write a script for nucleic acids but it won't be as good as a real python programmer can do ;p

**Comment by pckroon** [comment]
What kind of index groups do you want? Per residue in the output system? Atoms-per-bead in the input system? Per molecule in the output system? Anything else?

**Comment by ifaust83** [comment]
The aim is to use the index files for the calculation of bonds, angles and dihedrals from the CG trajectory. In the meantime, I have found a solution using MDAnalysis (thanks to some old files from Jaakko) to coarse-grain the atomistic trajectory and output the corresponding distributions. I'll let you know how it goes.

**Comment by jbarnoud** [comment]
Just for the record, I have a plan to make a binding to MDAnalysis for that specific purpose.
